# Generated by Django 6.0.5 on 2026-05-24 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_campus', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion_fisica', models.CharField(max_length=300)),
                ('provincia', models.CharField(max_length=100)),
                ('infraestructura_compartida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='CohorteDeMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_registro', models.CharField(max_length=50, unique=True)),
                ('fecha_de_cierre', models.DateField()),
                ('tipo_de_cohorte', models.CharField(choices=[('Primera matrícula', 'Primera matrícula'), ('Segunda matrícula', 'Segunda matrícula'), ('Exoneración', 'Exoneración')], max_length=50)),
                ('estado_de_cohorte', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=50)),
                ('total_primera_matricula', models.IntegerField(default=0)),
                ('total_segunda_matricula', models.IntegerField(default=0)),
                ('total_exonerados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cohorte de matrícula',
                'verbose_name_plural': 'Cohortes de matrícula',
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_paralelo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=50)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('capacidad_maxima', models.IntegerField(default=35)),
            ],
            options={
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
            },
        ),
        migrations.CreateModel(
            name='PeriodoDeNivelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_periodo', models.CharField(max_length=50, unique=True)),
                ('anio', models.IntegerField()),
                ('periodo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('numero_periodo', models.IntegerField()),
                ('estado', models.CharField(choices=[('Planificación', 'Planificación'), ('En curso', 'En curso'), ('Evaluación', 'Evaluación'), ('Cerrado', 'Cerrado')], default='Planificación', max_length=50)),
            ],
            options={
                'verbose_name': 'Periodo de nivelación',
                'verbose_name_plural': 'Periodos de nivelación',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=20)),
                ('codigo_sniese', models.CharField(max_length=50, unique=True)),
                ('direccion_matriz', models.CharField(max_length=300)),
                ('identificador_visual', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipo_de_identificacion', models.CharField(choices=[('Cédula', 'Cédula'), ('Pasaporte', 'Pasaporte'), ('Cédula extranjera', 'Cédula extranjera')], max_length=50)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('etnia', models.CharField(max_length=50)),
                ('porcentaje_de_discapacidad', models.FloatField(default=0.0)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=300)),
                ('estado_de_usuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario del sistema',
                'verbose_name_plural': 'Usuarios del sistema',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_carrera', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('campo_de_conocimiento', models.CharField(max_length=200)),
                ('vigencia_sniese', models.DateField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='core.campus')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_malla', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area_de_conocimiento', models.CharField(max_length=200)),
                ('duracion_semanas', models.IntegerField()),
                ('version_de_malla', models.CharField(max_length=20)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('estado', models.CharField(choices=[('Diseño', 'Diseño'), ('Activa', 'Activa'), ('Histórica', 'Histórica'), ('Inactiva', 'Inactiva')], default='Diseño', max_length=50)),
                ('total_horas_nivelacion', models.FloatField(default=0.0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mallas_curriculares', to='core.carrera')),
            ],
            options={
                'verbose_name': 'Malla curricular',
                'verbose_name_plural': 'Mallas curriculares',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('espacio_de_imparticion', models.CharField(max_length=200)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial')], max_length=50)),
                ('numero_semana', models.IntegerField()),
                ('tipo_de_sesion', models.CharField(choices=[('Sincrónica', 'Sincrónica'), ('Asincrónica', 'Asincrónica'), ('Evaluación', 'Evaluación')], max_length=50)),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.paralelo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilAdministrativoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_administrativo', models.CharField(max_length=50, unique=True)),
                ('perfil_administrativo', models.CharField(choices=[('Rector', 'Rector'), ('Vicerrector académico', 'Vicerrector académico'), ('Director de dirección de admisión y nivelación', 'Director de dirección de admisión y nivelación'), ('Coordinador de dirección de admisión y nivelación ', 'Coordinador de dirección de admisión y nivelación '), ('Coordinador de unidad académica', 'Coordinador de unidad académica')], max_length=50)),
                ('usuario_de_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrativo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil administrativo',
                'verbose_name_plural': 'Perfiles administrativos',
            },
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_institucional', models.CharField(max_length=50, unique=True)),
                ('tipo_de_vinculacion', models.CharField(choices=[('Nombramiento', 'Nombramiento'), ('Contrato', 'Contrato'), ('Ocasional', 'Ocasional'), ('Honorario', 'Honorario')], max_length=50)),
                ('tiempo_de_dedicacion', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Tiempo parcial', 'Tiempo parcial')], max_length=50)),
                ('estado_de_vinculacion', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Licencia temporal', 'Licencia temporal')], default='Activo', max_length=50)),
                ('carga_horaria_maxima', models.FloatField(default=40.0)),
                ('carga_horaria_actual', models.FloatField(default=0.0)),
                ('especialidades', models.JSONField(default=list)),
                ('usuario_de_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil docente',
                'verbose_name_plural': 'Perfiles docentes',
            },
        ),
        migrations.AddField(
            model_name='paralelo',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelos', to='core.perfildocente'),
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_institucional', models.CharField(max_length=50, unique=True)),
                ('numero_de_matricula', models.CharField(max_length=50, unique=True)),
                ('jornada', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], max_length=50)),
                ('registro_de_cupo', models.CharField(choices=[('Registro regular', 'Registro regular'), ('Segunda matrícula', 'Segunda matrícula'), ('Proceso de exoneración', 'Proceso de exoneración')], max_length=50)),
                ('estado_de_matricula', models.CharField(choices=[('Aspirante', 'Aspirante'), ('Pendiente de pago', 'Pendiente de pago'), ('Matriculado', 'Matriculado'), ('Retirado', 'Retirado'), ('Anulada', 'Anulada')], default='Aspirante', max_length=50)),
                ('campus_registrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='core.campus')),
                ('carrera_registrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='core.carrera')),
                ('usuario_de_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil estudiante',
                'verbose_name_plural': 'Perfiles estudiantes',
            },
        ),
        migrations.AddField(
            model_name='paralelo',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='core.periododenivelacion'),
        ),
        migrations.CreateModel(
            name='InformeGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_informe', models.CharField(max_length=100, unique=True)),
                ('tipo_de_informe', models.CharField(choices=[('Planificación', 'Planificación'), ('Avance', 'Avance'), ('Final', 'Final')], max_length=50)),
                ('estado_de_informe', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('Aprobado', 'Aprobado')], default='Borrador', max_length=50)),
                ('fecha_de_emision', models.DateField(blank=True, null=True)),
                ('cohortes', models.ManyToManyField(blank=True, related_name='informes', to='core.cohortedematricula')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='core.periododenivelacion')),
            ],
            options={
                'verbose_name': 'Informe general',
                'verbose_name_plural': 'Informes generales',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_corte', models.DateField()),
                ('total_cupos_aceptados', models.IntegerField(default=0)),
                ('registros_totales', models.IntegerField(default=0)),
                ('registros_validos', models.IntegerField(default=0)),
                ('registros_observados', models.IntegerField(default=0)),
                ('periodo_academico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consolidado_academico', to='core.periododenivelacion')),
            ],
            options={
                'verbose_name': 'Consolidado académico',
                'verbose_name_plural': 'Consolidados académicos',
            },
        ),
        migrations.AddField(
            model_name='cohortedematricula',
            name='periodo_de_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes_de_matricula', to='core.periododenivelacion'),
        ),
        migrations.CreateModel(
            name='UnidadCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_unidad', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area_de_conocimiento', models.JSONField(default=list)),
                ('horas_totales', models.FloatField()),
                ('horas_semanales', models.FloatField()),
                ('horas_sincronicas', models.FloatField()),
                ('horas_asincronicas', models.FloatField()),
                ('tipo_de_componente', models.CharField(choices=[('Teórico', 'Teórico'), ('Práctico', 'Práctico'), ('Tutorial', 'Tutorial')], max_length=50)),
                ('criterio_de_aprobacion', models.FloatField(default=7.0)),
                ('porcentaje_minimo_asistencia', models.FloatField(default=70.0)),
                ('malla_curricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_curriculares', to='core.mallacurricular')),
            ],
            options={
                'verbose_name': 'Unidad curricular',
                'verbose_name_plural': 'Unidades curriculares',
            },
        ),
        migrations.AddField(
            model_name='paralelo',
            name='unidad_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='core.unidadcurricular'),
        ),
        migrations.AddField(
            model_name='periododenivelacion',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='core.universidad'),
        ),
        migrations.AddField(
            model_name='campus',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus', to='core.universidad'),
        ),
        migrations.CreateModel(
            name='MatriculaParalelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cohorte_de_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.cohortedematricula')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_matriculados', to='core.paralelo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_matriculados', to='core.perfilestudiante')),
            ],
            options={
                'verbose_name': 'Matrícula en paralelo',
                'verbose_name_plural': 'Matrículas en paralelos',
                'unique_together': {('estudiante', 'paralelo')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_parcial_1', models.FloatField(default=0.0)),
                ('calificacion_parcial_2', models.FloatField(default=0.0)),
                ('nota_final', models.FloatField(default=0.0)),
                ('porcentaje_asistencia', models.FloatField(default=0.0)),
                ('estado_de_aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Retirado', 'Retirado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=50)),
                ('observacion', models.TextField(blank=True, default='')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_academicas', to='core.perfilestudiante')),
                ('unidad_curricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_academicas', to='core.unidadcurricular')),
            ],
            options={
                'verbose_name': 'Evaluación académica',
                'verbose_name_plural': 'Evaluaciones académicas',
                'unique_together': {('estudiante', 'unidad_curricular')},
            },
        ),
    ]
