# Generated by Django 6.0.5 on 2026-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfiladministrativomodel_perfil_administrativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfilAdministrativoModel',
            new_name='PerfilAdministrativo',
        ),
    ]
